- name: Install PHP
  package:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
      - httpd
      - php
      - php-xml
      - php-mysql
      - php-gd
      - php-intl
      - php-mbstring
      - firewalld
      - php-fpm
      - php-mariadb
      - php-xcache
      - php-pear-MDB2-Driver-mysql

- name: enable service php-fpm and ensure it is not masked
  systemd:
    name: php-fpm
    enabled: yes
    masked: no
